development:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_development
  pool: 5
  username: beracus
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_test
  pool: 5
  username: beracus
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_production
  pool: 5
  username: beracus
  password:
