development:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_development
  pool: 5
  username: beracus
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_test
  pool: 5
  username: beracus
  password:
  # host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_production
  pool: 5
  username: beracus
  password:
