development:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_development
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_test
  pool: 5
  port: 5432
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: sevendaysports_production
  pool: 5
